### PR TITLE
Add GitHub Action docker build, remove travis-ci

### PR DESCRIPTION
**Pull request by neilcook**

### CODE REVIEW

**Comment by neilcook** [comment]
Github is still waiting for travis even though I removed .travis.yml, but I guess this is because I need to disable travis in the repo

**Comment by Habbie** [comment]
> Github is still waiting for travis even though I removed .travis.yml, but I guess this is because I need to disable travis in the repo

it's in Branch protection settings

**Comment by neilcook** [comment]
> > Github is still waiting for travis even though I removed .travis.yml, but I guess this is because I need to disable travis in the repo
> 
> it's in Branch protection settings

Cool, thanks - I was looking for it and couldn't remember where!

**Comment by neilcook** [comment]
Sooo looking forward to pulling there trigger on this and leaving travis behind...

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
> Sooo looking forward to pulling the trigger on this and leaving travis behind...

dooo iiiiit

**Pull request merged**
