### PR TITLE
Reorganize sources

### PR DESCRIPTION
**Pull request by cmouse**
- Do not install headers
- Move ext to one directory
- Build json11 and yahttp as library

### CODE REVIEW

**Comment by cmouse** [comment]
Installation is reduced to 
```
/home/cmouse/wf/share/man/man1/wforce.1
/home/cmouse/wf/bin/wforce
/home/cmouse/wf/etc/wforce.conf
/home/cmouse/wf/etc/wforce.conf.example
```

**Comment by Habbie** [comment]
Both .conf and .conf.example is on purpose?

**Comment by cmouse** [comment]
This was result of make install to new location. I did not look but afaik the .conf is installed intentionally.

**Comment by neilcook** [comment]
Yes.

.conf is a working simple confit

.conf.example is a kind of tutorial of what is possible

Neil

**Pull request merged**
